language: python

python:
  - "3.6"

install:
  - pip install mkdocs pymdown-extensions

script:
  - mkdocs build

deploy:
  skip-cleanup: true
  provider: script
  script:
    - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
    - mkdocs gh-deploy --force
  on:
    condition: $TRAVIS_PULL_REQUEST == false

branches:
  only:
    - master
