language: python

python:
  - "3.6"

# Fake X Server for wkhtmltopdf
dist: xenial
services:
  - xvfb

# Installation des dépendances requises
install:
  - pip install -r source/requirements.txt
  - sudo apt-get update && sudo apt-get install -y texlive-full

# Compilation des docs
script:
  - make html

# Compilation des docs en une page unique et conversion en pdf
before_deploy:
  - sphinx-build -b singlehtml source build/singlehtml
  - sudo apt-get install -y wkhtmltopdf
  - wkhtmltopdf ./build/singlehtml/index.html Tutoriel.pdf

# Creation d'une release Github du pdf
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "Tutoriel.pdf"
  name: Build n°${TRAVIS_BUILD_NUMBER} - $(date +'%d.%m.%Y')
  skip_cleanup: true

branches:
  only:
    - master
