language: python

python:
  - "3.6"

install:
  - pip install mkdocs pymdown-extensions
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
  - mkdocs build

deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then mkdocs gh-deploy --force; fi'

branches:
  only:
    - master
