language: python

python:
  - "3.6"

install:
  - pip install mkdocs pymdown-extensions
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
  - mkdocs gh-deploy --force

branches:
  only:
    - master
