site_name: Cours WpiLib

site_author: FRC 5553 - Robo'Lyon Team
repo_url: https://github.com/Team5553-RoboLyon/Cours-WpiLib
copyright: Copyright &copy; 2019, FRC 5553 - Robo'Lyon.


theme:
    name: readthedocs
    custom_dir: custom_theme/

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
